before_script:
  - docker info

stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
      - shell
  script:
    - echo "Running tests"

build-staging:
  stage: build
  tags:
    - shell
  script:
    - docker build -t $IMAGE_NAME_LATEST -f Dockerfile .

  only:
    -  staging

build-production:
  stage: build
  tags:
    - shell
  script:
    - docker build -t $IMAGE_NAME_LATEST -f Dockerfile .

  only:
    -  master
