stages:
  - test
  - build

test:
  stage: test
  tags:
      - shell
  script:
    - echo "Running tests"

build-staging:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login registry.gitlab.com --username gidox --password -TV^KxuX@X_43%f
  script:
    - docker build -t registry.gitlab.com/writersdormteam/$IMAGE_NAME_LATEST -f Dockerfile.k8s .
    - docker push registry.gitlab.com/writersdormteam/$IMAGE_NAME_LATEST